apiVersion: v1
kind: Service
metadata:
  name: castled-app-service
spec:
  type: ClusterIP
  ports:
    - port: 7050
      protocol: TCP
  selector:
    castled: app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: castled-app
spec:
  replicas: 1
  selector:
    matchLabels:
      castled: app
  template:
    metadata:
      labels:
        castled: app
    spec:
      volumes:
        - name: configs
          secret:
            secretName: castled-configs
      containers:
        - name: castled-app-container
          image: castled/app
          env:
            - name: APP_KAFKA_HOST
              valueFrom:
                configMapKeyRef:
                  name: castled-env
                  key: KAFKA_HOST
            - name: APP_REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: castled-env
                  key: REDIS_HOST
            - name: APP_REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: castled-env
                  key: REDIS_PORT
            - name: APP_LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: castled-env
                  key: LOG_LEVEL
            - name: APP_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: castled-secrets
                  key: DATABASE_URL
            - name: APP_DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: castled-secrets
                  key: DATABASE_USER
            - name: APP_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: castled-secrets
                  key: DATABASE_PASSWORD
          volumeMounts:
            - name: configs
              readOnly: true
              mountPath: "/app/configs"
          ports:
            - containerPort: 7050
