apiVersion: v1
kind: Service
metadata:
  name: castled-db-service
spec:
  type: ClusterIP
  ports:
    - port: 3306
      protocol: TCP
  selector:
    castled: db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: castled-db
spec:
  replicas: 1
  selector:
    matchLabels:
      castled: db
  template:
    metadata:
      labels:
        castled: db
    spec:
      containers:
        - name: castled-db-container
          image: mysql:5.7.15
          args: ["--ignore-db-dir=lost+found"]
          env:
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: castled-secrets
                  key: DATABASE_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: castled-secrets
                  key: DATABASE_PASSWORD
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: castled-secrets
                  key: DATABASE_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: castled-secrets
                  key: DATABASE_DB
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: castled-db-vol
              mountPath: /var/lib/mysql
      volumes:
        - name: castled-db-vol
          persistentVolumeClaim:
            claimName: castled-db-vol
