apiVersion: v1
kind: Service
metadata:
  name: castled-kafka-service
spec:
  type: ClusterIP
  ports:
    - port: 9092
      protocol: TCP
  selector:
    castled: kafka
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: castled-kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      castled: kafka
  template:
    metadata:
      labels:
        castled: kafka
    spec:
      containers:
        - name: castled-kafka-container
          image: confluentinc/cp-kafka:5.3.0
          env:
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_ZOOKEEPER_CONNECT
              valueFrom:
                configMapKeyRef:
                  name: castled-env
                  key: ZOOKEEPER_HOST
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://castled-kafka-service:9092,PLAINTEXT_INTERNAL://localhost:29092"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT"
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: "PLAINTEXT"
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
          ports:
            - containerPort: 9092
          volumeMounts:
            - name: castled-kafka-vol
              mountPath: /var/lib/kafka/data
              subPath: kdata
      volumes:
        - name: castled-kafka-vol
          persistentVolumeClaim:
            claimName: castled-kafka-vol
