apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: castled-db-vol
  labels:
    castled: db-vol
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: castled-kafka-vol
  labels:
    castled: kafka-vol
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: castled-zookeeper-data-vol
  labels:
    castled: zookeeper-data-vol
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: castled-zookeeper-log-vol
  labels:
    castled: zookeeper-log-vol
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
