apiVersion: v1
kind: Service
metadata:
  name: castled-webapp-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    castled: webapp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: castled-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      castled: webapp
  template:
    metadata:
      labels:
        castled: webapp
    spec:
      containers:
        - name: castled-webapp-container
          image: castled/webapp
          env:
            - name: API_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: castled-env
                  key: API_BASE_URL
            - name: API_BASE
              valueFrom:
                configMapKeyRef:
                  name: castled-env
                  key: API_BASE
            - name: APP_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: castled-env
                  key: APP_BASE_URL
          ports:
            - containerPort: 3000
