version: "3.8"

x-logging: &default-logging
  options:
    max-size: "120m"
    max-file: "5"
  driver: json-file

services:
  db:
    image: mysql:5.7
    platform: linux/amd64
    container_name: castled-db
    restart: unless-stopped
    logging: *default-logging
    environment:
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_DATABASE=${DATABASE_DB}
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - ${DATABASE_PORT}:3306
    volumes:
      - db_vol:/var/lib/mysql

  app:
    image: castled/app:${VERSION}
    container_name: castled-app
    restart: unless-stopped
    logging: *default-logging
    environment:
      - APP_KAFKA_HOST=${KAFKA_HOST}
      - APP_REDIS_HOST=${REDIS_HOST}
      - APP_REDIS_PORT=${REDIS_PORT}
      - APP_DATABASE_URL=${DATABASE_URL}
      - APP_DATABASE_USER=${DATABASE_USER}
      - APP_DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - APP_LOG_LEVEL=${LOG_LEVEL}
      - OAUTH_GOOGLE_CLIENT_ID=${OAUTH_GOOGLE_CLIENT_ID}
      - OAUTH_GOOGLE_CLIENT_SECRET=${OAUTH_GOOGLE_CLIENT_SECRET}
      - OAUTH_HUBSPOT_CLIENT_ID=${OAUTH_HUBSPOT_CLIENT_ID}
      - OAUTH_HUBSPOT_CLIENT_SECRET=${OAUTH_HUBSPOT_CLIENT_SECRET}
      - OAUTH_SALESFORCE_CLIENT_ID=${OAUTH_SALESFORCE_CLIENT_ID}
      - OAUTH_SALESFORCE_CLIENT_SECRET=${OAUTH_SALESFORCE_CLIENT_SECRET}
      - OAUTH_MICROSOFT_CLIENT_ID=${OAUTH_MICROSOFT_CLIENT_ID}
      - OAUTH_MICROSOFT_CLIENT_SECRET=${OAUTH_MICROSOFT_CLIENT_SECRET}
      - S3_BUCKET=${S3_BUCKET}
      - S3_BUCKET_REGION=${S3_BUCKET_REGION}
    ports:
      - 7050:7050

  zookeeper:
    image: confluentinc/cp-zookeeper:5.3.0
    container_name: castled-zookeeper
    restart: unless-stopped
    logging: *default-logging
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
    ports:
      - ${ZOOKEEPER_PORT}:2181
    volumes:
      - zk_data:/var/lib/zookeeper/data
      - zk_log:/var/lib/zookeeper/log

  kafka:
    image: confluentinc/cp-kafka:5.3.0
    container_name: castled-kafka
    restart: unless-stopped
    logging: *default-logging
    depends_on:
      - zookeeper
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=${ZOOKEEPER_HOST}
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://${KAFKA_HOST},PLAINTEXT_INTERNAL://localhost:29092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    ports:
      - 20902:29092
    volumes:
      - kafka_vol:/var/lib/kafka/data

  redis:
    image: redis:6.2-alpine
    container_name: castled-redis
    logging: *default-logging
    restart: unless-stopped

  webapp:
    image: castled/webapp:${VERSION}
    container_name: castled-webapp
    restart: unless-stopped
    logging: *default-logging
    environment:
      - API_BASE=${API_BASE}
      - API_BASE_URL=${API_BASE_URL}
      - APP_BASE_URL=${APP_BASE_URL}
    ports:
      - 3000:3000

volumes:
  kafka_vol:
    name: ${KAFKA_DOCKER_MOUNT}
  db_vol:
    name: ${DB_DOCKER_MOUNT}
  zk_log:
    name: ${ZK_LOG_DOCKER_MOUNT}
  zk_data:
    name: ${ZK_DATA_DOCKER_MOUNT}
