apiVersion: v1
kind: Service
metadata:
  name: {{ include "castled.fullname" . }}-kafka-service
spec:
  type: {{ .Values.kafka.service.type }}
  ports:
    - port: 9092
      protocol: TCP
  selector:
    castled: kafka