apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "castled.fullname" . }}-zookeeper-data-vol
  labels:
    castled: zookeeper-data-vol
spec:
  accessModes:
  - {{ .Values.zookeeper.data.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.zookeeper.data.persistence.size | quote }}
  {{- include "common.storage.class" (dict "persistence" .Values.zookeeper.data.persistence "global" .Values.global) | nindent 2 }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "castled.fullname" . }}-zookeeper-log-vol
  labels:
    castled: zookeeper-log-vol
spec:
  accessModes:
  - {{ .Values.zookeeper.log.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.zookeeper.log.persistence.size | quote }}
  {{- include "common.storage.class" (dict "persistence" .Values.zookeeper.log.persistence "global" .Values.global) | nindent 2 }}