apiVersion: v1
kind: Service
metadata:
  name: {{ include "castled.fullname" . }}-zookeeper-service
spec:
  type: {{ .Values.zookeeper.service.type }}
  ports:
    - port: 2181
      protocol: TCP
  selector:
    castled : zookeeper