apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "castled.fullname" . }}-db
  labels:
    {{- include "castled.labels" . | nindent 4 }}
spec:
  {{- if not .Values.db.autoscaling.enabled }}
  replicas: {{ .Values.db.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "castled.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.db.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        castled: db
    spec:
      containers:
        - name: castled-db-container
          image: "{{ .Values.db.image.repository }}:{{ .Values.db.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.db.image.pullPolicy }}
          args: ["--ignore-db-dir=lost+found"]
          ports:
            - name: http
              containerPort: 3306
              protocol: TCP
          resources:
            {{- toYaml .Values.db.resources | nindent 12 }}
          env:
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: castled-secrets
                  key: DATABASE_USER
            - name: MYSQL_PASSWORD # The DB engine to use
              valueFrom:
                secretKeyRef:
                  name: castled-secrets
                  key: DATABASE_PASSWORD
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: castled-secrets
                  key: DATABASE_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: castled-secrets
                  key: DATABASE_DB
      volumes:
        - name: castled-db-vol
          persistentVolumeClaim:
            claimName: castled-db-vol
      {{- with .Values.db.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.db.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}