apiVersion: v1
kind: Service
metadata:
  name: {{ include "castled.fullname" . }}-db-service
spec:
  type: {{ .Values.db.service.type }}
  ports:
    - port: 3306
      protocol: TCP
  selector:
    castled : db