apiVersion: v1
kind: Service
metadata:
  name: {{ include "castled.fullname" . }}-app-service
spec:
  type: {{ .Values.app.service.type }}
  ports:
    - port: {{ .Values.app.service.port }}
      targetPort: 7050
      protocol: TCP
      name: http
  selector:
    castled : app