name: Castled Docker Image CI

on:
  workflow_dispatch:
    inputs:
      partToBump:
        description: "Please choose the type of sem version upgrade : major|minor|patch"
        required: true
        default: "patch"

jobs:
  publishCastled:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: "11"
          cache: "maven"

      - name: Get Old Version
        id: old_version
        run: echo ::set-output name=OLD_VERSION::$(grep VERSION .env | cut -d"=" -f2)

      - name: Version Bump
        env:
          PART_TO_BUMP: ${{ github.event.inputs.partToBump }}
        run: ./tools/bin/bump_release_version.sh

      - name: Release Maven package
        uses: samuelmeuli/action-maven-publish@v1
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg_passphrase: ${{ secrets.GPG_PASSPHRASE }}
          nexus_username: ${{ secrets.NEXUS_USERNAME }}
          nexus_password: ${{ secrets.NEXUS_PASSWORD }}
          maven_profiles: release

      - name: Build Jar
        run: mvn clean package

      - name: Release Docker Images
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: ./tools/bin/docker_release.sh

      - name: Get New Version
        id: new_version
        run: echo ::set-output name=NEW_VERSION::$(grep VERSION .env | cut -d"=" -f2)

      - name: Create Pull Request
        id: pr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GH_ACTION_PAT }}
          branch: bump-version
          branch-suffix: short-commit-hash
          delete-branch: true
          title: Bumping Castled version from ${{ steps.old_version.outputs.OLD_VERSION }} to ${{ steps.new_version.outputs.NEW_VERSION }}
          body: Bumping Castled version
          commit-message: Bumping Castled version from ${{ steps.old_version.outputs.OLD_VERSION }} to ${{ steps.new_version.outputs.NEW_VERSION }}

      - name: Pull Request Info
        run: echo "Pull Request Url - ${{ steps.pr.outputs.pull-request-url }}"
